export const CATEGORIES = [
  "Food & Dining",
  "Transportation",
  "Housing",
  "Entertainment",
  "Shopping",
  "Healthcare",
  "Education",
  "Travel",
  "Personal Care",
  "Gifts & Donations",
  "Investments",
  "Income",
  "Betting",
  "Subscriptions",
  "Bills",
  "Other",
]
